"""ASS subtitle export. Emits a complete .ass string from a TimelineManifest.

Orchestration lives in main; this module only turns the shared manifest +
template preset into subtitles so both outputs (ASS and draft keyframes)
describe the same scene.
"""
import math

from word_video import template

_HEADER = [
    '[Script Info]',
    '; Generated by word_video.render.ass',
    'ScriptType: v4.00+',
    'PlayResX: {width}',
    'PlayResY: {height}',
    'WrapStyle: 2',
    'ScaledBorderAndShadow: yes',
    'YCbCr Matrix: TV.709',
    '',
    '[V4+ Styles]',
    'Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, '
    'OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, '
    'ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, '
    'MarginL, MarginR, MarginV, Encoding',
]
_EVENT_FORMAT = ('Format: Layer, Start, End, Style, Name, MarginL, MarginR, '
                 'MarginV, Effect, Text')


def _num(value):
    value = float(value)
    if value.is_integer():
        return str(int(value))
    return f'{value:g}'


def _cs(frame, fps):
    """Frames -> centiseconds, rounding halves up."""
    frame, fps = int(frame), int(fps)
    return (frame * 200 + fps) // (2 * fps)


def _timestamp(centiseconds):
    cs = max(0, int(centiseconds))
    h, cs = divmod(cs, 360000)
    m, cs = divmod(cs, 6000)
    s, cs = divmod(cs, 100)
    return f'{h}:{m:02d}:{s:02d}.{cs:02d}'


def _color(value):
    text = str(value).strip().lstrip('#')
    if len(text) == 8:  # AARRGGBB -> drop leading alpha
        text = text[2:]
    if len(text) != 6:
        text = 'FFFFFF'
    r, g, b = text[0:2], text[2:4], text[4:6]
    return f'&H00{b}{g}{r}&'


def _escape_text(text):
    """Neutralize user text so it cannot inject ASS override tags."""
    text = str(text)
    text = text.replace('\\', '\\\\').replace('{', '\\{').replace('}', '\\}')
    text = text.replace('\r\n', '\n').replace('\r', '\n')
    return text.replace('\n', '\\N')


def _styles(manifest):
    merged = {name: dict(style) for name, style in template.default_styles().items()}
    for name, override in (manifest.styles or {}).items():
        merged.setdefault(name, {}).update(override or {})
    # libass can only use faces handed to it through fontsdir, so an unusable
    # resolved face (deleted by a Jianying cache purge) would drop text silently.
    if any(not style.get('font') for style in merged.values()):
        raise ValueError('No usable font for a rendered style; run doctor')
    return merged


def _style_line(name, style, height):
    size = float(style.get('size', 100)) * height / 2160.0
    # The family name must exist inside fontsdir or libass renders nothing, so a
    # resolved style always carries the name read from its own file.
    font = style.get('font_name') or style.get('font') or 'Arial'
    color = _color(style.get('color', '#FFFFFF'))
    bold = -1 if style.get('bold') else 0
    return (f'Style: {name},{font},{_num(size)},{color},{color},&H00000000&,'
            f'&HCC000000&,{bold},0,0,0,100,100,0,0,1,0,{_num(5*height/2160)},5,0,0,0,1')


def _anchor(style, width, height):
    x = float(style.get('x', 0.5)) * width
    y = float(style.get('y', 0.5)) * height
    return f'\\an5\\pos({_num(x)},{_num(y)})'


def _countdown_tags():
    # Scale 125 -> 100 and fade alpha FF -> 00 over the first 150 ms.
    return '\\fscx125\\fscy125\\alpha&HFF&\\t(0,150,\\fscx100\\fscy100\\alpha&H00&)'


def build_ass(manifest, offset_frames=0, frame_limit=None):
    """Return a full ASS document for the manifest. Performs no file writes.

    ``offset_frames``/``frame_limit`` render one *slice* of the timeline: every
    event is shifted back to the slice's own zero and clipped to it, and events
    outside the slice are dropped.  Slicing exists because libass composites on a
    single thread and is by far the most expensive stage of the render; running
    the slices as separate processes is what makes the render parallel.
    """
    style_map = _styles(manifest)
    lines = [line.format(width=manifest.width, height=manifest.height)
             for line in _HEADER]
    for name, style in style_map.items():
        lines.append(_style_line(name, style, manifest.height))
    lines.extend(['', '[Events]', _EVENT_FORMAT])

    fps = manifest.fps
    for track, text, start, end in template.text_events(manifest):
        style = style_map.get(track)
        if style is None:
            continue
        if frame_limit is not None:
            start = max(start, offset_frames)
            end = min(end, offset_frames + frame_limit)
            if end <= start:
                continue
        start_cs = _cs(start - offset_frames, fps)
        end_cs = max(_cs(end - offset_frames, fps), start_cs + 1)
        tags = _anchor(style, manifest.width, manifest.height)
        if track == 'countdown' and style.get('animation') == 'candidate_pulse':
            tags += _countdown_tags()
        lines.append(f'Dialogue: 0,{_timestamp(start_cs)},{_timestamp(end_cs)},'
                     f'{track},,0,0,0,,{{{tags}}}{_escape_text(text)}')
    return '\n'.join(lines) + '\n'
