"""The one clock a continuous preview runs on: PCM samples the sink really played.

Why a *single* clock, and why the audio one
-------------------------------------------
A preview that lets the video player and the audio player each keep their own
clock drifts, and no amount of "resync when it looks wrong" fixes it: the two
rates are generated by different hardware and the error accumulates.  So there
is exactly one time source - the number of PCM frames the audio device has
actually consumed - and everything else (which video frame, which text, which
clip is "now") is a pure function of it.  Audio cannot drift from itself, and
video that is late is late in a way we can see and choose to drop.

Consequences the rest of the package relies on:

* **The clock never runs ahead of the sound.**  A sink that has nothing to play
  does not advance, so a starving mixer stalls the picture instead of running it
  on and then jumping back.  The frame queue therefore never has to be "caught
  up" by throwing time away.
* **A seek is a new generation.**  ``reanchor`` bumps
  :attr:`AudioClock.generation`; every frame and every PCM block carries the
  generation it was produced for, and anything from an older one is dropped
  rather than played late.  That is what stops the previous position's audio
  from being heard after a seek.
* **Position is derived, never accumulated.**  ``position_ticks`` recomputes from
  the sink's frame counter, so a paused/blocked UI thread cannot make the
  timeline creep.

The abstract :class:`AudioOutput` is deliberately tiny: the Qt implementation
lives in ``desktop/audio_qt.py`` so this package stays importable - and testable -
without Qt, and :class:`ManualAudioOutput` lets a test move the clock by an exact
number of frames instead of waiting for real time.
"""
from dataclasses import dataclass
from enum import Enum
from typing import Protocol, runtime_checkable

from word_video.domain.timebase import TICKS_PER_SECOND

__all__ = ['AudioClock', 'AudioOutput', 'ManualAudioOutput', 'NullAudioOutput',
           'PlaybackState', 'ticks_for_frames', 'frames_for_ticks']

#: Output latency kept for the device buffer.  100 ms is short enough that a seek
#: is heard immediately and long enough that a 20 ms mixer window cannot starve
#: the device on a busy machine.
DEFAULT_BUFFER_FRAMES = 4800


def ticks_for_frames(frames, rate):
    """Frames on ``rate`` -> project ticks, exactly (integer maths, no float)."""
    if rate <= 0:
        raise ValueError('rate must be positive')
    return frames * TICKS_PER_SECOND // rate


def frames_for_ticks(ticks, rate):
    """Project ticks -> frames on ``rate``, rounded down (never past the tick)."""
    if rate <= 0:
        raise ValueError('rate must be positive')
    if ticks < 0:
        raise ValueError('ticks must not be negative')
    return ticks * rate // TICKS_PER_SECOND


class PlaybackState(Enum):
    """Where a preview session is; ``RELEASED`` is terminal."""

    IDLE = 'idle'
    PLAYING = 'playing'
    PAUSED = 'paused'
    ENDED = 'ended'
    RELEASED = 'released'


@runtime_checkable
class AudioOutput(Protocol):
    """A PCM sink that can report how much of what it was given has been heard.

    ``frames_played`` is the clock, so it must count *consumed* frames, not
    accepted ones: a sink that reports every byte it buffered would make the
    picture lead the sound by the whole device buffer.
    """

    rate: int

    def start(self) -> None:
        """Open the device.  ``frames_played`` counts from here."""

    def write(self, pcm: bytes) -> int:
        """Queue ``pcm`` (mono s16); return the bytes accepted (0 when full)."""

    def free_frames(self) -> int:
        """How many frames may be written right now without dropping any."""

    def frames_played(self) -> int:
        """Frames the device has actually played since :meth:`start`."""

    def flush(self) -> None:
        """Throw away everything buffered but not yet heard, and re-zero the count.

        This is the operation that makes a seek honest: without it the device
        keeps playing the old position for up to a whole buffer after the
        timeline has already moved.
        """

    def stop(self) -> None:
        """Stop playing; the device may be started again."""

    def close(self) -> None:
        """Release the device for good."""


class NullAudioOutput:
    """A sink with no device: accepts everything, plays it as fast as asked.

    Used by ``--no-audio`` runs (a machine with no output device, a CI box) and
    by the layout/queue tests.  ``frames_played`` follows the wall clock, so the
    session still paces itself instead of rendering the whole lesson at once -
    a null sink that reported instant completion would turn a preview into a
    batch job.
    """

    def __init__(self, rate=48000, buffer_frames=DEFAULT_BUFFER_FRAMES, clock=None):
        self.rate = int(rate)
        self.buffer_frames = int(buffer_frames)
        self._clock = clock
        self._accepted = 0
        self._started_at = None
        self._flushed_at = 0

    def start(self):
        import time
        self._started_at = time.monotonic()
        self._accepted = 0
        self._flushed_at = 0

    def write(self, pcm):
        frames = len(pcm) // 2
        self._accepted += frames
        return len(pcm)

    def free_frames(self):
        # Lead the wall clock by at most one device buffer.
        return max(0, self.buffer_frames - (self._accepted - self.frames_played()))

    def frames_played(self):
        import time
        if self._started_at is None:
            return 0
        elapsed = time.monotonic() - self._started_at
        wall = int(elapsed * self.rate)
        return min(self._accepted, wall) + self._flushed_at

    def flush(self):
        # Everything accepted but not yet "heard" is dropped; the count restarts
        # from what has been played so far, which is what the device does too.
        self._flushed_at = self.frames_played()
        self._accepted = self._flushed_at

    def stop(self):
        self._started_at = None

    def close(self):
        self._started_at = None
        self._accepted = 0
        self._flushed_at = 0


@dataclass
class ManualAudioOutput:
    """A sink whose clock only moves when a test moves it.

    ``advance(n)`` is "the device played ``n`` more frames"; ``write`` never
    changes the clock.  Tests for generation drops, bounded queues and resource
    release therefore run in microseconds and give the same answer every time,
    instead of depending on how fast the machine happened to be.
    """

    rate: int = 48000
    buffer_frames: int = DEFAULT_BUFFER_FRAMES
    played: int = 0
    buffered: int = 0
    written: int = 0
    flushes: int = 0
    started: bool = False
    closed: bool = False
    #: Every block accepted, as ``(generation, first_frame, frames)``.
    log: list = None

    def __post_init__(self):
        if self.log is None:
            self.log = []

    # -- test controls ---------------------------------------------------
    def advance(self, frames):
        """The device has now played ``frames`` more frames of what it holds."""
        taken = min(frames, self.buffered)
        self.buffered -= taken
        self.played += taken
        return taken

    def advance_all(self):
        return self.advance(self.buffered)

    # -- AudioOutput -----------------------------------------------------
    def start(self):
        self.started = True
        self.played = 0
        self.buffered = 0
        self.flushes = 0

    def write(self, pcm):
        frames = len(pcm) // 2
        free = self.free_frames()
        if frames > free:
            return 0
        self.buffered += frames
        self.written += frames
        return len(pcm)

    def note(self, generation, first_frame, frames):
        """Record provenance of an accepted block (tests assert on this)."""
        self.log.append((generation, first_frame, frames))

    def free_frames(self):
        return max(0, self.buffer_frames - self.buffered)

    def frames_played(self):
        return self.played

    def flush(self):
        self.flushes += 1
        self.buffered = 0

    def stop(self):
        self.started = False
        self.buffered = 0

    def close(self):
        self.closed = True
        self.buffered = 0


class AudioClock:
    """Timeline position derived from a sink's played-frame counter.

    The clock stores an *anchor*: the timeline tick that corresponds to the
    sink's frame count at the moment the current generation started.  Position
    is then ``anchor + ticks(played - frames_at_anchor)``.  Nothing accumulates,
    so reading the clock twice without the sink moving gives the same answer and
    a dropped UI frame cannot make the timeline drift.
    """

    def __init__(self, rate, total_ticks):
        if rate <= 0:
            raise ValueError('rate must be positive')
        if total_ticks < 0:
            raise ValueError('total_ticks must not be negative')
        self.rate = int(rate)
        self.total_ticks = int(total_ticks)
        self._state = PlaybackState.IDLE
        self._generation = 0
        self._anchor_ticks = 0
        self._frames_at_anchor = 0

    # -- state -----------------------------------------------------------
    @property
    def state(self):
        return self._state

    @property
    def generation(self):
        """Monotonic id of the current play position; bumps on every seek."""
        return self._generation

    @property
    def anchor_ticks(self):
        return self._anchor_ticks

    @property
    def frames_at_anchor(self):
        return self._frames_at_anchor

    def set_state(self, state):
        self._state = state
        return state

    # -- generations -----------------------------------------------------
    def begin(self, at_ticks, frames_played):
        """Start the first generation at ``at_ticks`` from a fresh sink."""
        return self.reanchor(at_ticks, frames_played)

    def reanchor(self, at_ticks, frames_played):
        """Move to ``at_ticks``; returns the new generation.

        Call this *after* flushing the sink, passing the sink's (re-zeroed)
        played count.  Every producer compares the generation it started with
        against :attr:`generation` and discards its output when they differ, so
        a decoder or mixer that was mid-block when the user seeked can never
        deliver the old position into the new one.
        """
        if at_ticks < 0:
            raise ValueError('at_ticks must not be negative')
        self._generation += 1
        self._anchor_ticks = min(int(at_ticks), self.total_ticks)
        self._frames_at_anchor = int(frames_played)
        return self._generation

    def is_current(self, generation):
        return generation == self._generation

    # -- position --------------------------------------------------------
    def position_ticks(self, frames_played):
        """Timeline position for a sink that has played ``frames_played``."""
        elapsed = max(0, int(frames_played) - self._frames_at_anchor)
        return min(self.total_ticks,
                   self._anchor_ticks + ticks_for_frames(elapsed, self.rate))

    def position_seconds(self, frames_played):
        return self.position_ticks(frames_played) / float(TICKS_PER_SECOND)

    def at_end(self, frames_played):
        return self.position_ticks(frames_played) >= self.total_ticks
